image: node:9.11.1

pages:
  cache:
    paths:
      - node_modules/

  script:
    - yarn install
    - yarn build-storybook
    - mv -fr storybook-static public

  artifacts:
    paths:
      - public

  only:
    - master
